# Generated by Django 4.2.4 on 2023-08-20 17:59

import code_review.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('new', 'New'), ('modified', 'Modified'), ('checked', 'Checked'), ('failed', 'Failed')])),
                ('file', models.FileField(upload_to=code_review.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['py'])])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
