# Generated by Django 4.2.4 on 2023-08-22 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='task_date',
            field=models.DateTimeField(blank=False),
            preserve_default=False,
        ),
    ]
