# Generated by Django 4.2.4 on 2023-08-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_review', '0002_file_task_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='task_date',
            new_name='start_datetime',
        ),
        migrations.AddField(
            model_name='file',
            name='period',
            field=models.TimeField(blank=False),
            preserve_default=False,
        ),
    ]
