version: "3.8"

services:
  app:
    build: ./
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    restart: always
    ports:
      - "80:8000"
    depends_on:
      - db
    volumes:
      - app_media:/app/media
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

  celery_worker:
    build:
      context: .
    entrypoint: celery
    command: -A skyeng worker -l info
    depends_on:
      - redis
      - db
    volumes:
      - app_media:/app/media

  celery_beat:
    build:
      context: .
    entrypoint: celery
    command: -A skyeng beat -l info
    depends_on:
      - redis
      - db
      - celery_worker
    volumes:
      - app_media:/app/media

volumes:
  postgres_data:
  app_media: